https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html

In [13]:
%%capture
nMC = 1000 #number of runs for MC simulation
r20 = np.array([iter_i_error(.2) for i in range(nMC)])

In [14]:
    m20 = np.array([np.mean(r20[:,i]) for i in range(5)])
    s20 = np.array([np.std(r20[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 20% missing rate')
    print(m20)
    print(s20)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 20% missing rate
[0.15014167 0.1339625  0.13375417 0.70351667 0.13585   ]
[0.02482887 0.023012   0.02271074 0.16174921 0.02287238]


In [15]:
%%capture
nMC = 1000 #number of runs for MC simulation
r35 = np.array([iter_i_error(.35) for i in range(nMC)])

In [16]:
    m35 = np.array([np.mean(r35[:,i]) for i in range(5)])
    s35 = np.array([np.std(r35[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 35% missing rate')
    print(m35)
    print(s35)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 35% missing rate
[0.15088333 0.13805417 0.13681667 0.71826667 0.14319167]
[0.02437449 0.02278116 0.02301762 0.16132215 0.02400522]


In [17]:
%%capture
nMC = 1000 #number of runs for MC simulation
r50 = np.array([iter_i_error(.5) for i in range(nMC)])

In [18]:
    m50 = np.array([np.mean(r50[:,i]) for i in range(5)])
    s50 = np.array([np.std(r50[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 50% missing rate')
    print(m50)
    print(s50)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 50% missing rate
[0.152725   0.14746667 0.14435    0.72409583 0.1533375 ]
[0.0253778  0.02490689 0.02421592 0.16116405 0.02732374]


In [19]:
%%capture
nMC = 1000 #number of runs for MC simulation
r65 = np.array([iter_i_error(.65) for i in range(nMC)])

In [20]:
    m65 = np.array([np.mean(r65[:,i]) for i in range(5)])
    s65 = np.array([np.std(r65[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 65% missing rate')
    print(m65)
    print(s65)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 65% missing rate
[0.15224167 0.16002083 0.14684167 0.71433333 0.16245417]
[0.02563044 0.03044946 0.02419662 0.16291232 0.03266594]


In [21]:
%%capture
nMC = 1000
#number of runs for MC simulation
r80 = np.array([iter_i_error(.8) for i in range(nMC)])

In [22]:
    m80 = np.array([np.mean(r80[:,i]) for i in range(5)])
    s80 = np.array([np.std(r80[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 80% missing rate')
    print(m80)
    print(s80)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 80% missing rate
[0.15300833 0.16718333 0.15113333 0.70077083 0.1691875 ]
[0.02745473 0.03410681 0.02576874 0.16436033 0.03788253]


In [24]:
assume_equal_cov_err = np.vstack((m20,m35,m50,m65,m80))
assume_equal_cov_err.round(3)

array([[0.15 , 0.134, 0.134, 0.704, 0.136],
       [0.151, 0.138, 0.137, 0.718, 0.143],
       [0.153, 0.147, 0.144, 0.724, 0.153],
       [0.152, 0.16 , 0.147, 0.714, 0.162],
       [0.153, 0.167, 0.151, 0.701, 0.169]])

In [ ]:
# column left to right: dper_err,mice_err, soft_err, resi_err, missf_err
# row0 -> row5 denote the missing rate from 20% -> 80%
assume_equal_cov_err = np.array([[0.15 , 0.134, 0.134, 0.704, 0.136],
       [0.151, 0.138, 0.137, 0.718, 0.143],
       [0.153, 0.147, 0.144, 0.724, 0.153],
       [0.152, 0.16 , 0.147, 0.714, 0.162],
       [0.153, 0.167, 0.151, 0.701, 0.169]])
not_assume_equal_cov_err = np.array([[0.106, 0.107, 0.109, 0.697, 0.107],
       [0.108, 0.112, 0.113, 0.716, 0.11 ],
       [0.11 , 0.121, 0.117, 0.714, 0.113],
       [0.113, 0.131, 0.121, 0.708, 0.118],
       [0.128, 0.153, 0.128, 0.711, 0.126]])

# Functions

In [1]:
    G=4
    def iter_i_error(missing_rate):
         # func to compute the misclassification rate for the i^{th} iteration
         # based on the al_err_func compute error function
         G, n_per_class = 4, 120
         mu_1, mu_2 = np.array([2,-2]), np.array([2,2])
         mu_3, mu_4 = np.array([-2,-2]), np.array([-2,2])
         S= np.array([[2,.8],[.8,2]])
         X_1 = np.random.multivariate_normal(mu_1,S,n_per_class)
         X_2 = np.random.multivariate_normal(mu_2,S,n_per_class)
         X_3 = np.random.multivariate_normal(mu_3,S,n_per_class)
         X_4 = np.random.multivariate_normal(mu_4,S,n_per_class)        
         X = np.vstack((X_1,X_2, X_3, X_4))
         y = np.hstack((np.repeat(0,n_per_class), np.repeat(1,n_per_class), 
                        np.repeat(2,n_per_class),np.repeat(3,n_per_class)))   
         Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.5)
         dper_err = compute_err_MLE(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         mice_err = compute_err_mice(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         soft_err = compute_err_SOFT(Xtrain, ytrain, Xtest, ytest, G, missing_rate);
         missf_err = compute_err_MissF(Xtrain, ytrain, Xtest, ytest, G, missing_rate);
         resi_err = compute_err_resi(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         return np.hstack((dper_err,mice_err, soft_err, resi_err, missf_err))

In [2]:
# !pip install impyute
# !pip install fancyimpute
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.model_selection import train_test_split
from sklearn.impute import IterativeImputer
from scipy import stats
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as skLDA
# import impyute as impy
from fancyimpute import SoftImpute
import pandas as pd
import math
import time
# !pip install missingpy
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
'''
In case importing missingpy result in the error
"No module named 'sklearn.neighbors._base'"
Then run the following
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
'''

'\nIn case importing missingpy result in the error\n"No module named \'sklearn.neighbors._base\'"\nThen run the following\nimport sklearn.neighbors._base\nimport sys\nsys.modules[\'sklearn.neighbors.base\'] = sklearn.neighbors._base\n'

In [3]:
def diag_term(i,X,y):
  arr0 = X[:,i]
  nar2 = 0
  arr = arr0[~np.isnan(arr0)]
  y_arr = y[~np.isnan(arr0)]

  _, counts = np.unique(y_arr, return_counts=True)
  ind = np.insert(np.cumsum(counts), 0, 0)
  
  return sum([(ind[g]-ind[g-1])*np.var(arr[ind[g-1]:ind[g]]) for 
                       g in range(1,G+1)])/len(y_arr)                       

In [4]:
def mle(X,y,G):
    '''
    X: input, should be a numpy array
    y: label
    G: number of classes
    output:
    - mus: each row is a class mean
    - S: common covariance matrix of class 1,2,..., G 
    '''
    epsilon = 1e-5 # define epsilon to put r down to 0 if r < epsilon
    n,p = X.shape[0], X.shape[1]

    # Estimating class means
    mus = np.array([np.nanmean(X[y==g,:],axis=0) for g in range (G)]).T # so that each column is the mean of a class
 
    S = np.diag([diag_term(i,X,y) for i in range(p)]) 

    for i in range(p):      
      for j in range(i):
        mat = X[:,[i,j]]

        # drop rows with NA
        idx = ~np.isnan(mat).any(axis=1)
        mat, y_arr = mat[idx], y[idx]

        _, counts = np.unique(y_arr, return_counts=True)
        ind = np.insert(np.cumsum(counts), 0, 0)

        m_g = counts
 
        A = len(y_arr) 
        scaled_mat = [mat[ind[g-1]:ind[g],:]-mus[[i,j],g-1] for g in range(1,G+1)]   

        q = lambda g: np.dot(scaled_mat[g][:,0],scaled_mat[g][:,0])
        s11 = sum(map(q,range(G))) 
        q = lambda g: np.dot(scaled_mat[g][:,1],scaled_mat[g][:,1])
        s22 = sum(map(q,range(G))) 
        d = lambda g: np.dot(scaled_mat[g][:,0],scaled_mat[g][:,1])
        s12 = sum(map(d,range(G)))  

        start_solve = time.time()
        B = S[i,i]*S[j,j]*A - s22 * S[i,i] - s11 * S[j,j]
        coefficient = [-A, s12, B, s12*S[i,i]*S[j,j]]
        r = np.roots(coefficient)

        r = r[abs(np.imag(r)) < epsilon]
        r = np.real(r)
        r[abs(r) < epsilon] = 0

        if len(r)>1:
          condi_var = S[j,j] - r**2/S[i,i]
          eta = -A*np.log(condi_var)-(S[j,j]-2*r/S[i,i]*s12 +
                                      r**2/S[i,i]**2*s11)/condi_var
          # if condi_var <0 then eta = NA. in practice, it's impossible for cov to be negative
          #  therefore, we drop NA elements of eta  
          r = r[eta == max(eta[~np.isnan(eta)])]

        if len(r) > 1:        
            w = [m_g[g-1]*np.cov(mat[ind[g-1]:ind[g],], rowvar=False) for
                 g in range(1,G+1)]
            w = np.sum(w, axis = 0)    
            r = r[np.abs(r-w[0,1]).argmin()] # select r that is closet to w[0,1] 
              
        S[i,j] = S[j,i] = r
    return [mus, S]

### compute_err function 
  

In [5]:
def lda_miss(mus, S, Xtest, ytrain, ytest, G):
    # This function is from https://github.com/thunguyen177/EPEM
    f = lambda g: np.log(np.mean(ytrain==g)) - np.matmul(
                  np.matmul(mus[:,g].T, np.linalg.inv(S)), mus[:,g]/2)
    last2 = [f(g) for g in np.arange(G)]
    
    h = lambda g,i: last2[g] + np.matmul(mus[:,g].T, np.matmul(
                    np.linalg.inv(S), Xtest[i,:].T))
    pred_label = [np.argmax([h(g,i) for g in np.arange(G)]) 
                  for i in np.arange(len(Xtest))]
    pred_label = np.asarray(pred_label)
    return np.mean(pred_label.flatten() != ytest)

In [6]:
def compute_err_MLE(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytrain = generate_nan(Xtrain,ytrain, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)
    
    # MLEs approach
    start = time.time()
    mus, S = mle(Xtr_nan, ytrain, G)
    mle_err = lda_miss(mus, S, Xtest, ytrain, ytest, G)
    mle_time = time.time()-start
    return mle_err#, mle_time
    
def compute_err_SOFT(Xtrain, ytr, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytr = generate_nan(Xtrain,ytr, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
    Xtr_softimpute = SoftImpute(max_iters = 100).fit_transform(Xtr_nan)
    clf_softimpute = skLDA().fit(Xtr_softimpute, ytr)
    softimpute_err = np.mean(clf_softimpute.predict(Xtest).flatten() != ytest)
    softimpute_time = time.time()-start

    return softimpute_err#, softimpute_time
def compute_err_MissF(Xtrain, ytr, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytr = generate_nan(Xtrain,ytr, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
    Xtr_missf = MissForest(random_state=0).fit_transform(Xtr_nan)
    clf_missf = skLDA().fit(Xtr_missf, ytr)
    missf_err = np.mean(clf_missf.predict(Xtest).flatten() != ytest)
    missf_time = time.time()-start

    return missf_err#, missf_time

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
def compute_err_mice(Xtrain, ytr, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytr = generate_nan(Xtrain,ytr, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
    Xtr_mice= IterativeImputer(max_iter=100).fit(Xtr_nan).transform(Xtr_nan)
    clf_mice= skLDA().fit(Xtr_mice, ytr)
    mice_err = np.mean(clf_mice.predict(Xtest).flatten() != ytest)
    mice_time = time.time()-start

    return mice_err#, mice_time


In [7]:
def compute_attribute_weights(A):
  from sklearn.preprocessing import minmax_scale
  y = minmax_scale(A, axis = 0)
  p = y.copy()
  ysum = y.sum(axis = 0)
  for i in range(y.shape[1]):
    if (ysum[i] == 0):
      p[:, i] = 1
    else:
      p[:, i] = y[:, i] / ysum[i]
  from scipy.special import xlogy
  E = - xlogy(p,p).sum(axis=0) / math.log(p.shape[0])
  w = (1 - E)/(len(E) - E.sum())
  if np.isnan(w).any():
    return None
  else:
    return w                                            
def generate_tuple_partition(CT, ICT, m):
  w = compute_attribute_weights(CT)
  r = np.ones(ICT.shape[0])
  for i in range(ICT.shape[0]):
    for j in range(ICT.shape[1]):
      if np.isnan(ICT[i,j]):
        r[i] -= w[j] #If NoneType then insufficient CT set has been used
  ICT = ICT[r.argsort()[::-1],:]
  return np.array_split(ICT, m)
def resi(Xtr_nan, m, n_neighbors):
  CT = [Xtr_nan[~np.isnan(Xtr_nan).any(axis=1)]]
  Tp = []
  T = generate_tuple_partition(CT[0],Xtr_nan[np.isnan(Xtr_nan).any(axis=1)], m)
  from sklearn.impute import KNNImputer
  for i in range(m):
    imputer = KNNImputer(n_neighbors=n_neighbors)
    imputer.fit(CT[-1])
    Tp.append(imputer.transform(T[i]))
    CT.append(np.concatenate((CT[-1],Tp[-1])))
  Tpp = []
  for i in range(m):
    train = CT[0]
    for j in range(1,m):
      if j != i:
        train = np.concatenate((train,T[j]))
    imputer = KNNImputer(n_neighbors=n_neighbors)
    imputer.fit(train)
    Tpp.append(imputer.transform(T[i]))
  imputer = KNNImputer(n_neighbors=n_neighbors)
  imputer.fit(CT[0])
  Tpp.append(imputer.transform(T[m-1]))
  CT = [CT[0]]
  for i in range(m):
    CT.append(np.concatenate((CT[-1],np.mean(np.array([Tp[i], Tpp[i]]), axis=0 ))))
  return CT[-1]

In [8]:
def generate_nan(Xtrain,ytr, missing_rate):
  minimum_complete_samples = 3
  ct_id = np.random.choice(range(Xtrain.shape[0]), size = minimum_complete_samples, replace = False)
  CT = Xtrain[ct_id]
  ICT = Xtrain[[i for i in range(Xtrain.shape[0]) if i not in ct_id]]
  ICTshape = ICT.shape
  na_id = np.random.randint(0,ICT.size, round(missing_rate*ICT.size))
  ICT = ICT.flatten()
  ICT[na_id] = np.nan
  xxx = np.concatenate((CT,ICT.reshape(ICTshape)))
  ytrain = np.hstack((ytr[ct_id], np.array([ytr[i] for i in range(Xtrain.shape[0]) if i not in ct_id])))
  return xxx, ytrain

In [9]:
def compute_err_resi(Xtrain, ytr, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytr = generate_nan(Xtrain,ytr, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
    Xtr_resi = resi(Xtr_nan, 3, 3) #Parameters: (Dataset, m, n_neighbors) 
    clf_mice= skLDA().fit(Xtr_resi, ytr)
    mice_err = np.mean(clf_mice.predict(Xtest).flatten() != ytest)
    mice_time = time.time()-start

    return mice_err#, mice_time