In [73]:
%%capture
nMC = 1000 #number of runs for MC simulation
r20 = np.array([iter_i_error(.2) for i in range(nMC)])

In [74]:
    m20 = np.array([np.mean(r20[:,i]) for i in range(5)])
    s20 = np.array([np.std(r20[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 20% missing rate')
    print(m20)
    print(s20)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 20% missing rate
[0.1059875  0.10737083 0.10949583 0.69689167 0.10698333]
[0.0202579  0.02035946 0.02060085 0.1575932  0.02073938]


In [75]:
%%capture
nMC = 1000 #number of runs for MC simulation
r35 = np.array([iter_i_error(.35) for i in range(nMC)])

In [76]:
    m35 = np.array([np.mean(r35[:,i]) for i in range(5)])
    s35 = np.array([np.std(r35[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 35% missing rate')
    print(m35)
    print(s35)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 35% missing rate
[0.10805417 0.11207917 0.11342083 0.7158625  0.11015417]
[0.02060395 0.02124052 0.02148569 0.14258195 0.02108351]


In [77]:
%%capture
nMC = 1000 #number of runs for MC simulation
r50 = np.array([iter_i_error(.5) for i in range(nMC)])

In [78]:
    m50 = np.array([np.mean(r50[:,i]) for i in range(5)])
    s50 = np.array([np.std(r50[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 50% missing rate')
    print(m50)
    print(s50)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 50% missing rate
[0.11007083 0.12112917 0.1173625  0.71365417 0.11348333]
[0.02058734 0.02379089 0.02234402 0.15076692 0.02186301]


In [70]:
%%capture
nMC = 1000 #number of runs for MC simulation
r65 = np.array([iter_i_error(.65) for i in range(nMC)])

In [71]:
    m65 = np.array([np.mean(r65[:,i]) for i in range(5)])
    s65 = np.array([np.std(r65[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 65% missing rate')
    print(m65)
    print(s65)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 65% missing rate
[0.11339167 0.13123333 0.12140417 0.70807083 0.11779167]
[0.02230634 0.02836517 0.02319985 0.14835048 0.02259744]


In [68]:
%%capture
nMC = 1000 #number of runs for MC simulation
r80 = np.array([iter_i_error(.8) for i in range(nMC)])

In [69]:
    m80 = np.array([np.mean(r80[:,i]) for i in range(5)])
    s80 = np.array([np.std(r80[:,i]) for i in range(5)])
    print('mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 80% missing rate')
    print(m80)
    print(s80)

mean and sd of dper_err,mice_err, soft_err, resi_err, missf_err at 80% missing rate
[0.12845417 0.15279167 0.12769583 0.7107625  0.12581667]
[0.07751476 0.04150617 0.02571019 0.12895851 0.02618629]


In [81]:
not_assume_equal_cov_err = np.vstack((m20,m35,m50,m65,m80))
not_assume_equal_cov_err.round(3)

array([[0.106, 0.107, 0.109, 0.697, 0.107],
       [0.108, 0.112, 0.113, 0.716, 0.11 ],
       [0.11 , 0.121, 0.117, 0.714, 0.113],
       [0.113, 0.131, 0.121, 0.708, 0.118],
       [0.128, 0.153, 0.128, 0.711, 0.126]])

## libraries and function 

In [67]:
    import math    
    from sklearn.model_selection import train_test_split
    def iter_i_error(missing_rate):   
         G, n_per_class = 4, 120
         mul = 2
         mu_1, mu_2 = mul*np.array([1,-1]), mul*np.array([1,1])
         mu_3, mu_4 = mul*np.array([-1,-1]), mul*np.array([-1,1])
         S_1, S_2 = np.array([[2,.7],[.7,2]]), np.array([[1.5,.5],[.5,1.5]])
         S_3, S_4 = np.array([[2,.9],[.9,2]]), np.array([[1.5,.7],[.7,1.5]])
         X_1 = np.random.multivariate_normal(mu_1,S_1,n_per_class)
         X_2 = np.random.multivariate_normal(mu_2,S_2,n_per_class)
         X_3 = np.random.multivariate_normal(mu_3,S_3,n_per_class)
         X_4 = np.random.multivariate_normal(mu_4,S_4,n_per_class)        
         X = np.vstack((X_1,X_2, X_3, X_4))
         y = np.hstack((np.repeat(0,n_per_class), np.repeat(1,n_per_class), 
                        np.repeat(2,n_per_class),np.repeat(3,n_per_class)))   
         Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.5)        
         
         dper_err = compute_err_MLE(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         mice_err = compute_err_mice(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         soft_err = compute_err_SOFT(Xtrain, ytrain, Xtest, ytest, G, missing_rate);
         missf_err = compute_err_MissF(Xtrain, ytrain, Xtest, ytest, G, missing_rate);
         resi_err = compute_err_resi(Xtrain, ytrain, Xtest, ytest, G, missing_rate)
         return np.hstack((dper_err,mice_err, soft_err, resi_err, missf_err))

In [2]:
# !pip install impyute
# !pip install fancyimpute
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy import stats
import numpy as np
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
# import impyute as impy
from fancyimpute import SoftImpute
import pandas as pd
import time
# !pip install missingpy
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
from missingpy import MissForest
'''
In case importing missingpy result in the error
"No module named 'sklearn.neighbors._base'"
Then run the following
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
'''

'\nIn case importing missingpy result in the error\n"No module named \'sklearn.neighbors._base\'"\nThen run the following\nimport sklearn.neighbors._base\nimport sys\nsys.modules[\'sklearn.neighbors.base\'] = sklearn.neighbors._base\n'

In [3]:
def diag_term(X,i):
  arr0 = X[:,i].flatten()
  arr = arr0[~np.isnan(arr0)]
  return np.var(arr)

def musMLE(X,y,G):
    n,p = X.shape[0], X.shape[1]
    f = lambda g: np.nanmean(X[y==g,:],axis=0)
    musMLE = np.array([f(g) for g in range(G)])    
    return musMLE.T

def Smle(X,y,musMLE,g):
    '''
    function to compute the covariance matrix for the g-th class
    X: input, should be a numpy array
    y: label
    G: number of classes
    g: class index
    output:
    - mus: each row is a class mean
    - S: common covariance matrix of class 1,2,..., G 
    '''
    epsilon = 1e-5 # define epsilon to put r down to 0 if r < epsilon
    Xg, yg = X[y==g,:], y[y==g]
    n,p = Xg.shape[0], Xg.shape[1] 
 
    S = np.diag([diag_term(Xg,i) for i in range(p)]) 

    for i in range(p):      
      for j in range(i):
        if ((S[i,i] == 0.) | (S[j,j] == 0.)):
          S[i,j] = S[j,i] = 0.
          continue

        mat = Xg[:,[i,j]]

        # drop rows with NA
        idx = ~np.isnan(mat).any(axis=1)
        mat, y_arr = mat[idx], yg[idx]
        A = mg = len(y_arr) 

        s11 = mg*np.var(mat[:,0])
        s22 = mg*np.var(mat[:,1])
        s12 = sum((mat[:,0]-musMLE[i,g])*(mat[:,1]-musMLE[j,g]))
        B = S[i,i]*S[j,j]*A - s22 * S[i,i] - s11 * S[j,j]
        coefficient = [-A, s12, B, s12*S[i,i]*S[j,j]]
        r = np.roots(coefficient)
        r = r[abs(np.imag(r)) < epsilon]
        r = np.real(r)
        r[abs(r) < epsilon] = 0
 
        if len(r)>1:
          condi_var = S[j,j] - r**2/S[i,i]
          eta = -A*np.log(condi_var)-(S[j,j]-2*r/S[i,i]*s12 + r**2/S[i,i]**2*s11)/condi_var
          r = r[eta == max(eta[~np.isnan(eta)])]

        if len(r) > 1: 
          if sum(r==0.0) == len(r):
            r = 0.
          else:  
            w = np.cov(mat, rowvar=False)  
            #r = r[w[0,1]*r>=0]
            r = r[np.abs(r-w[0,1]).argmin()] # select r that is closet to w[0,1] 

        S[i,j] = S[j,i] = r
    return S

In [4]:
def generate_nan(Xtrain, missing_rate):
  Xshape = Xtrain.shape
  na_id = np.random.randint(0,Xtrain.size,round(missing_rate*Xtrain.size))
  Xtr_nan = Xtrain.flatten()
  Xtr_nan[na_id] = np.nan 
  return Xtr_nan.reshape(Xshape) 
def qda_miss(mus, S, Xtest, ytrain, ytest, G):
#         mus: each row is a class mean
# S: the ith component is the covariance matrix of the g^th class
    pi = np.array([np.sum(ytrain==i) for i in range(G)])/len(ytrain) #vector of prior probabilities
    f = lambda g: np.log(pi[g]) - np.log(np.linalg.det(S[g]))/2
#     print(pi)
    class_terms = [f(g) for g in np.arange(G)]
#     print(class_terms)
#     print(np.array([np.linalg.det(S[g]) for g in range(G)]))
    
    h = lambda g,i: class_terms[g] - np.matmul((Xtest[i,:]-mus[:,g]).T, np.matmul(
                    np.linalg.inv(S[g]), (Xtest[i,:]-mus[:,g]).T))/2
    pred_label = [np.argmax([h(g,i) for g in np.arange(G)]) 
                  for i in np.arange(len(Xtest))]
    pred_label = np.asarray(pred_label)
    return np.mean(pred_label.flatten() != ytest)

In [5]:
def compute_err_MLE(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan,ytrain = generate_nan(Xtrain,ytrain, missing_rate)
    scaler = StandardScaler() 
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)
    
    Xtrain = scaler.transform(Xtrain)
    # MLEs approach
    start = time.time()
    mus_mle = musMLE(Xtr_nan,ytrain,G)
    S_mle = np.array([Smle(Xtr_nan,ytrain,mus_mle, g) for g in range(G)])   
    mle_err = qda_miss(mus_mle, S_mle, Xtest, ytrain, ytest, G)
    mle_time = time.time()-start
    return mle_err#, mle_time
    
def compute_err_SOFT(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan, ytrain = generate_nan(Xtrain, ytrain, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
#     Xtr_softimpute = SoftImpute(max_iters = 100).fit_transform(Xtr_nan)
    Xtr_missf = np.array([SoftImpute(max_iters = 100, verbose = False).fit_transform(Xtr_nan[ytrain==g]) for g in range(G)])
    Xtr_missf = np.concatenate(Xtr_missf, axis = 0)
    ytrain = np.array([np.repeat(g, sum(ytrain==g)) for g in range(G)])
    ytrain = np.concatenate(ytrain, axis = 0)
    clf_softimpute = QuadraticDiscriminantAnalysis().fit(Xtr_missf, ytrain)
    softimpute_err = np.mean(clf_softimpute.predict(Xtest).flatten() != ytest)
    softimpute_time = time.time()-start

    return softimpute_err#, softimpute_time

In [6]:
def compute_err_MissF(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan, ytrain = generate_nan(Xtrain, ytrain, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)
    
    start = time.time()
#     Xtr_missf = MissForest(random_state=0).fit_transform(Xtr_nan)
    Xtr_missf = np.array([MissForest(random_state=0, verbose = False).fit_transform(Xtr_nan[ytrain==g]) for g in range(G)])
    Xtr_missf = np.concatenate(Xtr_missf, axis = 0)
    ytrain = np.array([np.repeat(g, sum(ytrain==g)) for g in range(G)])
    ytrain = np.concatenate(ytrain, axis = 0)
    clf_missf = QuadraticDiscriminantAnalysis().fit(Xtr_missf, ytrain)
    missf_err = np.mean(clf_missf.predict(Xtest).flatten() != ytest)
    missf_time = time.time()-start

    return missf_err#, missf_time

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
def compute_err_mice(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
    # missing_rate: missing rate on training set
    Xtr_nan, ytrain = generate_nan(Xtrain, ytrain, missing_rate)
    scaler = StandardScaler()
    scaler.fit(Xtr_nan)
    Xtr_nan = scaler.transform(Xtr_nan)
    Xtest = scaler.transform(Xtest)

    start = time.time()
#     Xtr_mice= IterativeImputer(max_iter=100).fit(Xtr_nan).transform(Xtr_nan)
    Xtr_missf = np.array([ IterativeImputer(max_iter=100).fit_transform(Xtr_nan[ytrain==g]) for g in range(G)])
    Xtr_mice = np.concatenate(Xtr_missf, axis = 0)
    ytrain = np.array([np.repeat(g, sum(ytrain==g)) for g in range(G)])
    ytrain = np.concatenate(ytrain, axis = 0)
    clf_mice= QuadraticDiscriminantAnalysis().fit(Xtr_mice, ytrain)
    mice_err = np.mean(clf_mice.predict(Xtest).flatten() != ytest)
    mice_time = time.time()-start

    return mice_err#, mice_time

In [7]:
def compute_attribute_weights(A):
  from sklearn.preprocessing import minmax_scale
  y = minmax_scale(A, axis = 0)
  p = y.copy()
  ysum = y.sum(axis = 0)
  for i in range(y.shape[1]):
    if (ysum[i] == 0):
      p[:, i] = 1
    else:
      p[:, i] = y[:, i] / ysum[i]
  from scipy.special import xlogy
  E = - xlogy(p,p).sum(axis=0) / math.log(p.shape[0])
  w = (1 - E)/(len(E) - E.sum())
  if np.isnan(w).any():
    return None
  else:
    return w                                            
def generate_tuple_partition(CT, ICT, m):
  w = compute_attribute_weights(CT)
  r = np.ones(ICT.shape[0])
  for i in range(ICT.shape[0]):
    for j in range(ICT.shape[1]):
      if np.isnan(ICT[i,j]):
        r[i] -= w[j] #If NoneType then insufficient CT set has been used
  ICT = ICT[r.argsort()[::-1],:]
  return np.array_split(ICT, m)
def resi(Xtr_nan, m, n_neighbors):
  CT = [Xtr_nan[~np.isnan(Xtr_nan).any(axis=1)]]
  Tp = []
  T = generate_tuple_partition(CT[0],Xtr_nan[np.isnan(Xtr_nan).any(axis=1)], m)
  from sklearn.impute import KNNImputer
  for i in range(m):
    imputer = KNNImputer(n_neighbors=n_neighbors)
    imputer.fit(CT[-1])
    Tp.append(imputer.transform(T[i]))
    CT.append(np.concatenate((CT[-1],Tp[-1])))
  Tpp = []
  for i in range(m):
    train = CT[0]
    for j in range(1,m):
      if j != i:
        train = np.concatenate((train,T[j]))
    imputer = KNNImputer(n_neighbors=n_neighbors)
    imputer.fit(train)
    Tpp.append(imputer.transform(T[i]))
  imputer = KNNImputer(n_neighbors=n_neighbors)
  imputer.fit(CT[0])
  Tpp.append(imputer.transform(T[m-1]))
  CT = [CT[0]]
  for i in range(m):
    CT.append(np.concatenate((CT[-1],np.mean(np.array([Tp[i], Tpp[i]]), axis=0 ))))
  return CT[-1]

In [8]:
def generate_nan(Xtrain,ytr, missing_rate):
  minimum_complete_samples = 3
  ct_id = np.random.choice(range(Xtrain.shape[0]), size = minimum_complete_samples, replace = False)
  CT = Xtrain[ct_id]
  ICT = Xtrain[[i for i in range(Xtrain.shape[0]) if i not in ct_id]]
  ICTshape = ICT.shape
  na_id = np.random.randint(0,ICT.size, round(missing_rate*ICT.size))
  ICT = ICT.flatten()
  ICT[na_id] = np.nan
  xxx = np.concatenate((CT,ICT.reshape(ICTshape)))
  ytrain = np.hstack((ytr[ct_id], np.array([ytr[i] for i in range(Xtrain.shape[0]) if i not in ct_id])))
  return xxx, ytrain

In [9]:
    def compute_err_resi(Xtrain, ytrain, Xtest, ytest, G, missing_rate):    
        # missing_rate: missing rate on training set
        Xtr_nan, ytrain = generate_nan(Xtrain,ytrain, missing_rate)
        scaler = StandardScaler()
        scaler.fit(Xtr_nan)
        Xtr_nan = scaler.transform(Xtr_nan)
        Xtest = scaler.transform(Xtest)
    
        start = time.time()
        Xtr_resi = resi(Xtr_nan, 3, 3) #Parameters: (Dataset, m, n_neighbors) 
        clf_resi= QuadraticDiscriminantAnalysis().fit(Xtr_resi, ytrain)
        resi_err = np.mean(clf_resi.predict(Xtest).flatten() != ytest)
        resi_time = time.time()-start
    
        return resi_err#, mice_time